name: build
on:
- push
- workflow_dispatch

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Run Pester tests
    steps:
    - uses: actions/checkout@v3
    - run: pwsh -f ./run-tests.ps1
    # Publish test results
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        nunit_files: "PesterTestResults.xml"

  run_gitversion:
    runs-on: ubuntu-latest
    name: Run GitVersion
    outputs:
      semver: ${{ steps.run_gitversion.outputs.semver }}
      major: ${{ steps.run_gitversion.outputs.major }}
      majorMinor: ${{ steps.run_gitversion.outputs.major }}.${{ steps.run_gitversion.outputs.minor }}
      preReleaseTag: ${{ steps.run_gitversion.outputs.preReleaseTag }}
    steps:
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install GitVersion
      run: |
        dotnet tool install -g GitVersion.Tool --version 5.8.0
        echo "/github/home/.dotnet/tools" >> $GITHUB_PATH

    - name: Run GitVersion
      id: run_gitversion
      run: |
        pwsh -noprofile -c 'dotnet-gitversion /diag'
        pwsh -noprofile -c '(dotnet-gitversion | ConvertFrom-Json).psobject.properties | % { echo "$($_.name)=$($_.value)" >> $env:GITHUB_ENV }'

    - run: |
        echo "SemVer: ${{ steps.run_gitversion.outputs.SemVer }}"

  gitversion_debug:
    runs-on: ubuntu-latest
    needs: run_gitversion
    steps:
    - run: |
        echo "SemVer    : ${{ needs.run_gitversion.outputs.semver }}"
        echo "Major     : ${{ needs.run_gitversion.outputs.major }}"
        echo "MajorMinor: ${{ needs.run_gitversion.outputs.majorMinor }}"
        echo "PreReleaseTag: ${{ needs.run_gitversion.outputs.preReleaseTag }}"
