name: build
on:
- push
- workflow_dispatch

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Run Pester tests
    steps:
    - uses: actions/checkout@v3
    - run: pwsh -f ./run-tests.ps1
    # Publish test results
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        nunit_files: "PesterTestResults.xml"

  run_gitversion:
    uses: ./gitversion.yml

  gitversion_debug:
    runs-on: ubuntu-latest
    needs: run_gitversion
    steps:
    - run: |
        echo "SemVer    : ${{ needs.run_gitversion.outputs.semver }}"
        echo "Major     : ${{ needs.run_gitversion.outputs.major }}"
        echo "MajorMinor: ${{ needs.run_gitversion.outputs.majorMinor }}"
        echo "PreReleaseTag: ${{ needs.run_gitversion.outputs.preReleaseTag }}"
